- name: daemon-reload
  command: systemctl daemon-reload
  become: true

- name: restart website
  systemd:
    name: "{{ service }}"
    state: restarted
    enabled: true
  become: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: true
