/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadPresignRouteImport } from './routes/api/upload/presign'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiUploadMultipartPresignPartsRouteImport } from './routes/api/upload/multipart/presign-parts'
import { Route as ApiUploadMultipartInitRouteImport } from './routes/api/upload/multipart/init'
import { Route as ApiUploadMultipartCompleteRouteImport } from './routes/api/upload/multipart/complete'
import { Route as ApiUploadMultipartAbortRouteImport } from './routes/api/upload/multipart/abort'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPresignRoute = ApiUploadPresignRouteImport.update({
  id: '/api/upload/presign',
  path: '/api/upload/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadMultipartPresignPartsRoute =
  ApiUploadMultipartPresignPartsRouteImport.update({
    id: '/api/upload/multipart/presign-parts',
    path: '/api/upload/multipart/presign-parts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadMultipartInitRoute = ApiUploadMultipartInitRouteImport.update({
  id: '/api/upload/multipart/init',
  path: '/api/upload/multipart/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadMultipartCompleteRoute =
  ApiUploadMultipartCompleteRouteImport.update({
    id: '/api/upload/multipart/complete',
    path: '/api/upload/multipart/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadMultipartAbortRoute = ApiUploadMultipartAbortRouteImport.update({
  id: '/api/upload/multipart/abort',
  path: '/api/upload/multipart/abort',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload/presign': typeof ApiUploadPresignRoute
  '/api/upload/multipart/abort': typeof ApiUploadMultipartAbortRoute
  '/api/upload/multipart/complete': typeof ApiUploadMultipartCompleteRoute
  '/api/upload/multipart/init': typeof ApiUploadMultipartInitRoute
  '/api/upload/multipart/presign-parts': typeof ApiUploadMultipartPresignPartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload/presign': typeof ApiUploadPresignRoute
  '/api/upload/multipart/abort': typeof ApiUploadMultipartAbortRoute
  '/api/upload/multipart/complete': typeof ApiUploadMultipartCompleteRoute
  '/api/upload/multipart/init': typeof ApiUploadMultipartInitRoute
  '/api/upload/multipart/presign-parts': typeof ApiUploadMultipartPresignPartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload/presign': typeof ApiUploadPresignRoute
  '/api/upload/multipart/abort': typeof ApiUploadMultipartAbortRoute
  '/api/upload/multipart/complete': typeof ApiUploadMultipartCompleteRoute
  '/api/upload/multipart/init': typeof ApiUploadMultipartInitRoute
  '/api/upload/multipart/presign-parts': typeof ApiUploadMultipartPresignPartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/upload/presign'
    | '/api/upload/multipart/abort'
    | '/api/upload/multipart/complete'
    | '/api/upload/multipart/init'
    | '/api/upload/multipart/presign-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/upload/presign'
    | '/api/upload/multipart/abort'
    | '/api/upload/multipart/complete'
    | '/api/upload/multipart/init'
    | '/api/upload/multipart/presign-parts'
  id:
    | '__root__'
    | '/'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/upload/presign'
    | '/api/upload/multipart/abort'
    | '/api/upload/multipart/complete'
    | '/api/upload/multipart/init'
    | '/api/upload/multipart/presign-parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiUploadPresignRoute: typeof ApiUploadPresignRoute
  ApiUploadMultipartAbortRoute: typeof ApiUploadMultipartAbortRoute
  ApiUploadMultipartCompleteRoute: typeof ApiUploadMultipartCompleteRoute
  ApiUploadMultipartInitRoute: typeof ApiUploadMultipartInitRoute
  ApiUploadMultipartPresignPartsRoute: typeof ApiUploadMultipartPresignPartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/presign': {
      id: '/api/upload/presign'
      path: '/api/upload/presign'
      fullPath: '/api/upload/presign'
      preLoaderRoute: typeof ApiUploadPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/presign-parts': {
      id: '/api/upload/multipart/presign-parts'
      path: '/api/upload/multipart/presign-parts'
      fullPath: '/api/upload/multipart/presign-parts'
      preLoaderRoute: typeof ApiUploadMultipartPresignPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/init': {
      id: '/api/upload/multipart/init'
      path: '/api/upload/multipart/init'
      fullPath: '/api/upload/multipart/init'
      preLoaderRoute: typeof ApiUploadMultipartInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/complete': {
      id: '/api/upload/multipart/complete'
      path: '/api/upload/multipart/complete'
      fullPath: '/api/upload/multipart/complete'
      preLoaderRoute: typeof ApiUploadMultipartCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/abort': {
      id: '/api/upload/multipart/abort'
      path: '/api/upload/multipart/abort'
      fullPath: '/api/upload/multipart/abort'
      preLoaderRoute: typeof ApiUploadMultipartAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiUploadPresignRoute: ApiUploadPresignRoute,
  ApiUploadMultipartAbortRoute: ApiUploadMultipartAbortRoute,
  ApiUploadMultipartCompleteRoute: ApiUploadMultipartCompleteRoute,
  ApiUploadMultipartInitRoute: ApiUploadMultipartInitRoute,
  ApiUploadMultipartPresignPartsRoute: ApiUploadMultipartPresignPartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
