/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as ApiUploadPresignRouteImport } from './routes/api/upload/presign'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SiteRegisterJamRouteImport } from './routes/_site/register/jam'
import { Route as SiteRegisterCampRouteImport } from './routes/_site/register/camp'
import { Route as ApiUploadMultipartPresignPartsRouteImport } from './routes/api/upload/multipart/presign-parts'
import { Route as ApiUploadMultipartInitRouteImport } from './routes/api/upload/multipart/init'
import { Route as ApiUploadMultipartCompleteRouteImport } from './routes/api/upload/multipart/complete'
import { Route as ApiUploadMultipartAbortRouteImport } from './routes/api/upload/multipart/abort'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const ApiUploadPresignRoute = ApiUploadPresignRouteImport.update({
  id: '/api/upload/presign',
  path: '/api/upload/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRegisterJamRoute = SiteRegisterJamRouteImport.update({
  id: '/register/jam',
  path: '/register/jam',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRegisterCampRoute = SiteRegisterCampRouteImport.update({
  id: '/register/camp',
  path: '/register/camp',
  getParentRoute: () => SiteRoute,
} as any)
const ApiUploadMultipartPresignPartsRoute =
  ApiUploadMultipartPresignPartsRouteImport.update({
    id: '/api/upload/multipart/presign-parts',
    path: '/api/upload/multipart/presign-parts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadMultipartInitRoute = ApiUploadMultipartInitRouteImport.update({
  id: '/api/upload/multipart/init',
  path: '/api/upload/multipart/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadMultipartCompleteRoute =
  ApiUploadMultipartCompleteRouteImport.update({
    id: '/api/upload/multipart/complete',
    path: '/api/upload/multipart/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadMultipartAbortRoute = ApiUploadMultipartAbortRouteImport.update({
  id: '/api/upload/multipart/abort',
  path: '/api/upload/multipart/abort',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/register/camp': typeof SiteRegisterCampRoute
  '/register/jam': typeof SiteRegisterJamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload/presign': typeof ApiUploadPresignRoute
  '/api/upload/multipart/abort': typeof ApiUploadMultipartAbortRoute
  '/api/upload/multipart/complete': typeof ApiUploadMultipartCompleteRoute
  '/api/upload/multipart/init': typeof ApiUploadMultipartInitRoute
  '/api/upload/multipart/presign-parts': typeof ApiUploadMultipartPresignPartsRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/': typeof SiteIndexRoute
  '/register/camp': typeof SiteRegisterCampRoute
  '/register/jam': typeof SiteRegisterJamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload/presign': typeof ApiUploadPresignRoute
  '/api/upload/multipart/abort': typeof ApiUploadMultipartAbortRoute
  '/api/upload/multipart/complete': typeof ApiUploadMultipartCompleteRoute
  '/api/upload/multipart/init': typeof ApiUploadMultipartInitRoute
  '/api/upload/multipart/presign-parts': typeof ApiUploadMultipartPresignPartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/register/camp': typeof SiteRegisterCampRoute
  '/_site/register/jam': typeof SiteRegisterJamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/upload/presign': typeof ApiUploadPresignRoute
  '/api/upload/multipart/abort': typeof ApiUploadMultipartAbortRoute
  '/api/upload/multipart/complete': typeof ApiUploadMultipartCompleteRoute
  '/api/upload/multipart/init': typeof ApiUploadMultipartInitRoute
  '/api/upload/multipart/presign-parts': typeof ApiUploadMultipartPresignPartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/register/camp'
    | '/register/jam'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/upload/presign'
    | '/api/upload/multipart/abort'
    | '/api/upload/multipart/complete'
    | '/api/upload/multipart/init'
    | '/api/upload/multipart/presign-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/register/camp'
    | '/register/jam'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/upload/presign'
    | '/api/upload/multipart/abort'
    | '/api/upload/multipart/complete'
    | '/api/upload/multipart/init'
    | '/api/upload/multipart/presign-parts'
  id:
    | '__root__'
    | '/_site'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_site/'
    | '/_site/register/camp'
    | '/_site/register/jam'
    | '/api/auth/$'
    | '/api/files/$'
    | '/api/upload/presign'
    | '/api/upload/multipart/abort'
    | '/api/upload/multipart/complete'
    | '/api/upload/multipart/init'
    | '/api/upload/multipart/presign-parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiUploadPresignRoute: typeof ApiUploadPresignRoute
  ApiUploadMultipartAbortRoute: typeof ApiUploadMultipartAbortRoute
  ApiUploadMultipartCompleteRoute: typeof ApiUploadMultipartCompleteRoute
  ApiUploadMultipartInitRoute: typeof ApiUploadMultipartInitRoute
  ApiUploadMultipartPresignPartsRoute: typeof ApiUploadMultipartPresignPartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/upload/presign': {
      id: '/api/upload/presign'
      path: '/api/upload/presign'
      fullPath: '/api/upload/presign'
      preLoaderRoute: typeof ApiUploadPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/register/jam': {
      id: '/_site/register/jam'
      path: '/register/jam'
      fullPath: '/register/jam'
      preLoaderRoute: typeof SiteRegisterJamRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/register/camp': {
      id: '/_site/register/camp'
      path: '/register/camp'
      fullPath: '/register/camp'
      preLoaderRoute: typeof SiteRegisterCampRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/upload/multipart/presign-parts': {
      id: '/api/upload/multipart/presign-parts'
      path: '/api/upload/multipart/presign-parts'
      fullPath: '/api/upload/multipart/presign-parts'
      preLoaderRoute: typeof ApiUploadMultipartPresignPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/init': {
      id: '/api/upload/multipart/init'
      path: '/api/upload/multipart/init'
      fullPath: '/api/upload/multipart/init'
      preLoaderRoute: typeof ApiUploadMultipartInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/complete': {
      id: '/api/upload/multipart/complete'
      path: '/api/upload/multipart/complete'
      fullPath: '/api/upload/multipart/complete'
      preLoaderRoute: typeof ApiUploadMultipartCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/multipart/abort': {
      id: '/api/upload/multipart/abort'
      path: '/api/upload/multipart/abort'
      fullPath: '/api/upload/multipart/abort'
      preLoaderRoute: typeof ApiUploadMultipartAbortRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteRegisterCampRoute: typeof SiteRegisterCampRoute
  SiteRegisterJamRoute: typeof SiteRegisterJamRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteRegisterCampRoute: SiteRegisterCampRoute,
  SiteRegisterJamRoute: SiteRegisterJamRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiUploadPresignRoute: ApiUploadPresignRoute,
  ApiUploadMultipartAbortRoute: ApiUploadMultipartAbortRoute,
  ApiUploadMultipartCompleteRoute: ApiUploadMultipartCompleteRoute,
  ApiUploadMultipartInitRoute: ApiUploadMultipartInitRoute,
  ApiUploadMultipartPresignPartsRoute: ApiUploadMultipartPresignPartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
